image: docker:latest
services:
  - docker:dind
variables:
  DOCKER_DRIVER: overlay2

stages:
  - build

.build_template: &build_definition
  stage: build
  only:
    refs:
      - branches
      - /^v(?:\d+\.)+\d+$/
    variables:
      - $VARIANT_TAG
      - $VARIANT_TAG_WITH_VERSION
      - $VARIANT_BUILD_DIR
  except:
      refs:
        - master
  before_script:
  - date '+%Y-%m-%d %H:%M:%S %z'

  # Login to Docker Hub registry
  - echo "${DOCKERHUB_REGISTRY_PASSWORD}" | docker login -u "${DOCKERHUB_REGISTRY_USER}" --password-stdin

  # Login to GitLab registry
  - echo "${CI_REGISTRY_PASSWORD}" | docker login -u "${CI_REGISTRY_USER}" --password-stdin "${CI_REGISTRY}"

  script:
  - date '+%Y-%m-%d %H:%M:%S %z'

  - docker build
    -t "${DOCKERHUB_REGISTRY_USER}/${CI_PROJECT_NAME}:${VARIANT_TAG}"
    -t "${DOCKERHUB_REGISTRY_USER}/${CI_PROJECT_NAME}:${VARIANT_TAG_WITH_VERSION}"
    -t "${CI_REGISTRY_IMAGE}:${VARIANT_TAG}"
    -t "${CI_REGISTRY_IMAGE}:${VARIANT_TAG_WITH_VERSION}"
    "${VARIANT_BUILD_DIR}"

  - date '+%Y-%m-%d %H:%M:%S %z'

  # Push to Docker Hub registry. E.g. 'namespace/my-project:tag'
  - docker push "${DOCKERHUB_REGISTRY_USER}/${CI_PROJECT_NAME}:${VARIANT_TAG}"
  - docker push "${DOCKERHUB_REGISTRY_USER}/${CI_PROJECT_NAME}:${VARIANT_TAG_WITH_VERSION}"

  # Push to GitLab registry. E.g. 'registry.gitlab.com/namespace/my-project:tag
  - docker push "${CI_REGISTRY_IMAGE}:${VARIANT_TAG}"
  - docker push "${CI_REGISTRY_IMAGE}:${VARIANT_TAG_WITH_VERSION}"

  after_script:
  - date '+%Y-%m-%d %H:%M:%S %z'

  # Log out of Docker Hub registry
  - docker logout

  # Log out of GitLab registry
  - docker logout "${CI_REGISTRY}"

build-opcache:
  <<: *build_definition
  variables:
    VARIANT_TAG: opcache
    VARIANT_TAG_WITH_VERSION: opcache-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/opcache

build-mysqli:
  <<: *build_definition
  variables:
    VARIANT_TAG: mysqli
    VARIANT_TAG_WITH_VERSION: mysqli-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/mysqli

build-gd:
  <<: *build_definition
  variables:
    VARIANT_TAG: gd
    VARIANT_TAG_WITH_VERSION: gd-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/gd

build-pdo:
  <<: *build_definition
  variables:
    VARIANT_TAG: pdo
    VARIANT_TAG_WITH_VERSION: pdo-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/pdo

build-memcached:
  <<: *build_definition
  variables:
    VARIANT_TAG: memcached
    VARIANT_TAG_WITH_VERSION: memcached-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/memcached

build-xdebug:
  <<: *build_definition
  variables:
    VARIANT_TAG: xdebug
    VARIANT_TAG_WITH_VERSION: xdebug-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/xdebug

build-opcache-mysqli-gd:
  <<: *build_definition
  variables:
    VARIANT_TAG: opcache-mysqli-gd
    VARIANT_TAG_WITH_VERSION: opcache-mysqli-gd-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/opcache-mysqli-gd

build-opcache-mysqli-gd-pdo:
  <<: *build_definition
  variables:
    VARIANT_TAG: opcache-mysqli-gd-pdo
    VARIANT_TAG_WITH_VERSION: opcache-mysqli-gd-pdo-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/opcache-mysqli-gd-pdo

build-opcache-mysqli-gd-pdo-memcached:
  <<: *build_definition
  variables:
    VARIANT_TAG: opcache-mysqli-gd-pdo-memcached
    VARIANT_TAG_WITH_VERSION: opcache-mysqli-gd-pdo-memcached-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/opcache-mysqli-gd-pdo-memcached

build-opcache-mysqli-gd-xdebug:
  <<: *build_definition
  variables:
    VARIANT_TAG: opcache-mysqli-gd-xdebug
    VARIANT_TAG_WITH_VERSION: opcache-mysqli-gd-xdebug-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/opcache-mysqli-gd-xdebug

build-opcache-mysqli-gd-pdo-xdebug:
  <<: *build_definition
  variables:
    VARIANT_TAG: opcache-mysqli-gd-pdo-xdebug
    VARIANT_TAG_WITH_VERSION: opcache-mysqli-gd-pdo-xdebug-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/opcache-mysqli-gd-pdo-xdebug

build-opcache-mysqli-gd-pdo-memcached-xdebug:
  <<: *build_definition
  variables:
    VARIANT_TAG: opcache-mysqli-gd-pdo-memcached-xdebug
    VARIANT_TAG_WITH_VERSION: opcache-mysqli-gd-pdo-memcached-xdebug-$CI_COMMIT_REF_NAME
    VARIANT_BUILD_DIR: variants/alpine/opcache-mysqli-gd-pdo-memcached-xdebug
